/**
 * Generated by `npm run gen:types`
 * Do not edit this file manually.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.4"
  }
  public: {
    Tables: {
      app_sessions: {
        Row: {
          created_at: string
          expires_at: string
          id: string
          ip_hash: string | null
          last_seen_at: string
          metadata: Json
          organization_id: string
          revoked_at: string | null
          role: Database["public"]["Enums"]["app_role"]
          user_agent: string | null
          user_id: string
        }
        Insert: {
          created_at?: string
          expires_at: string
          id?: string
          ip_hash?: string | null
          last_seen_at?: string
          metadata?: Json
          organization_id: string
          revoked_at?: string | null
          role: Database["public"]["Enums"]["app_role"]
          user_agent?: string | null
          user_id: string
        }
        Update: {
          created_at?: string
          expires_at?: string
          id?: string
          ip_hash?: string | null
          last_seen_at?: string
          metadata?: Json
          organization_id?: string
          revoked_at?: string | null
          role?: Database["public"]["Enums"]["app_role"]
          user_agent?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "app_sessions_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "app_sessions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "app_users"
            referencedColumns: ["id"]
          },
        ]
      }
      app_users: {
        Row: {
          created_at: string
          display_name: string
          email: string | null
          failed_pin_attempts: number
          id: string
          is_active: boolean
          last_failed_at: string | null
          last_login_at: string | null
          locked_until: string | null
          metadata: Json
          organization_id: string
          pin_hash: string
          pin_lookup: string
          role: Database["public"]["Enums"]["app_role"]
          updated_at: string
        }
        Insert: {
          created_at?: string
          display_name: string
          email?: string | null
          failed_pin_attempts?: number
          id?: string
          is_active?: boolean
          last_failed_at?: string | null
          last_login_at?: string | null
          locked_until?: string | null
          metadata?: Json
          organization_id: string
          pin_hash: string
          pin_lookup: string
          role?: Database["public"]["Enums"]["app_role"]
          updated_at?: string
        }
        Update: {
          created_at?: string
          display_name?: string
          email?: string | null
          failed_pin_attempts?: number
          id?: string
          is_active?: boolean
          last_failed_at?: string | null
          last_login_at?: string | null
          locked_until?: string | null
          metadata?: Json
          organization_id?: string
          pin_hash?: string
          pin_lookup?: string
          role?: Database["public"]["Enums"]["app_role"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "app_users_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      auth_audit_logs: {
        Row: {
          attempted_lookup: string | null
          created_at: string
          event_type: string
          id: number
          ip_hash: string | null
          metadata: Json
          organization_id: string | null
          user_agent: string | null
          user_id: string | null
        }
        Insert: {
          attempted_lookup?: string | null
          created_at?: string
          event_type: string
          id?: never
          ip_hash?: string | null
          metadata?: Json
          organization_id?: string | null
          user_agent?: string | null
          user_id?: string | null
        }
        Update: {
          attempted_lookup?: string | null
          created_at?: string
          event_type?: string
          id?: never
          ip_hash?: string | null
          metadata?: Json
          organization_id?: string | null
          user_agent?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "auth_audit_logs_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "auth_audit_logs_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "app_users"
            referencedColumns: ["id"]
          },
        ]
      }
      billing_number_counters: {
        Row: {
          billing_date: string
          last_number: number
          organization_id: string
        }
        Insert: {
          billing_date: string
          last_number?: number
          organization_id: string
        }
        Update: {
          billing_date?: string
          last_number?: number
          organization_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "billing_number_counters_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      billing_number_counters_yearly: {
        Row: {
          billing_year: number
          last_number: number
          organization_id: string
        }
        Insert: {
          billing_year: number
          last_number?: number
          organization_id: string
        }
        Update: {
          billing_year?: number
          last_number?: number
          organization_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "billing_number_counters_yearly_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      billing_records: {
        Row: {
          billing_date: string
          billing_number: string
          created_at: string
          created_by: string | null
          customer_id: string
          from_date: string
          id: string
          organization_id: string
          snapshot_rows: Json | null
          to_date: string
          total_amount: number
        }
        Insert: {
          billing_date: string
          billing_number: string
          created_at?: string
          created_by?: string | null
          customer_id: string
          from_date: string
          id?: string
          organization_id: string
          snapshot_rows?: Json | null
          to_date: string
          total_amount: number
        }
        Update: {
          billing_date?: string
          billing_number?: string
          created_at?: string
          created_by?: string | null
          customer_id?: string
          from_date?: string
          id?: string
          organization_id?: string
          snapshot_rows?: Json | null
          to_date?: string
          total_amount?: number
        }
        Relationships: [
          {
            foreignKeyName: "billing_records_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "billing_records_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      customer_code_counters: {
        Row: {
          last_number: number
          organization_id: string
        }
        Insert: {
          last_number?: number
          organization_id: string
        }
        Update: {
          last_number?: number
          organization_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "customer_code_counters_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: true
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      customer_product_prices: {
        Row: {
          created_at: string
          customer_id: string
          id: string
          organization_id: string
          product_id: string
          product_sale_unit_id: string
          sale_price: number
          updated_at: string
        }
        Insert: {
          created_at?: string
          customer_id: string
          id?: string
          organization_id: string
          product_id: string
          product_sale_unit_id: string
          sale_price: number
          updated_at?: string
        }
        Update: {
          created_at?: string
          customer_id?: string
          id?: string
          organization_id?: string
          product_id?: string
          product_sale_unit_id?: string
          sale_price?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "customer_product_prices_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "customer_product_prices_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "customer_product_prices_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "customer_product_prices_product_sale_unit_id_fkey"
            columns: ["product_sale_unit_id"]
            isOneToOne: false
            referencedRelation: "product_sale_units"
            referencedColumns: ["id"]
          },
        ]
      }
      customers: {
        Row: {
          address: string
          created_at: string
          customer_code: string
          default_vehicle_id: string | null
          district: string | null
          id: string
          is_active: boolean
          line_user_id: string | null
          metadata: Json
          name: string
          organization_id: string
          phone: string | null
          postal_code: string | null
          province: string | null
          subdistrict: string | null
          updated_at: string
        }
        Insert: {
          address: string
          created_at?: string
          customer_code: string
          default_vehicle_id?: string | null
          district?: string | null
          id?: string
          is_active?: boolean
          line_user_id?: string | null
          metadata?: Json
          name: string
          organization_id: string
          phone?: string | null
          postal_code?: string | null
          province?: string | null
          subdistrict?: string | null
          updated_at?: string
        }
        Update: {
          address?: string
          created_at?: string
          customer_code?: string
          default_vehicle_id?: string | null
          district?: string | null
          id?: string
          is_active?: boolean
          line_user_id?: string | null
          metadata?: Json
          name?: string
          organization_id?: string
          phone?: string | null
          postal_code?: string | null
          province?: string | null
          subdistrict?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "customers_default_vehicle_id_fkey"
            columns: ["default_vehicle_id"]
            isOneToOne: false
            referencedRelation: "vehicles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "customers_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      delivery_note_counters: {
        Row: {
          last_number: number
          organization_id: string
        }
        Insert: {
          last_number?: number
          organization_id: string
        }
        Update: {
          last_number?: number
          organization_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "delivery_note_counters_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: true
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      delivery_note_counters_yearly: {
        Row: {
          delivery_year: number
          last_number: number
          organization_id: string
        }
        Insert: {
          delivery_year: number
          last_number?: number
          organization_id: string
        }
        Update: {
          delivery_year?: number
          last_number?: number
          organization_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "delivery_note_counters_yearly_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      delivery_note_items: {
        Row: {
          created_at: string
          delivery_note_id: string
          id: string
          line_total: number
          order_item_id: string | null
          organization_id: string
          product_id: string
          product_sale_unit_id: string | null
          quantity_delivered: number
          quantity_in_base_unit: number
          sale_unit_label: string
          sale_unit_ratio: number
          unit_price: number
        }
        Insert: {
          created_at?: string
          delivery_note_id: string
          id?: string
          line_total?: number
          order_item_id?: string | null
          organization_id: string
          product_id: string
          product_sale_unit_id?: string | null
          quantity_delivered: number
          quantity_in_base_unit: number
          sale_unit_label: string
          sale_unit_ratio?: number
          unit_price?: number
        }
        Update: {
          created_at?: string
          delivery_note_id?: string
          id?: string
          line_total?: number
          order_item_id?: string | null
          organization_id?: string
          product_id?: string
          product_sale_unit_id?: string | null
          quantity_delivered?: number
          quantity_in_base_unit?: number
          sale_unit_label?: string
          sale_unit_ratio?: number
          unit_price?: number
        }
        Relationships: [
          {
            foreignKeyName: "delivery_note_items_delivery_note_id_fkey"
            columns: ["delivery_note_id"]
            isOneToOne: false
            referencedRelation: "delivery_notes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "delivery_note_items_order_item_id_fkey"
            columns: ["order_item_id"]
            isOneToOne: false
            referencedRelation: "order_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "delivery_note_items_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "delivery_note_items_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "delivery_note_items_product_sale_unit_id_fkey"
            columns: ["product_sale_unit_id"]
            isOneToOne: false
            referencedRelation: "product_sale_units"
            referencedColumns: ["id"]
          },
        ]
      }
      delivery_notes: {
        Row: {
          created_at: string
          created_by: string | null
          customer_id: string
          delivery_date: string
          delivery_number: string
          dispatch_note: string | null
          dispatch_status: string
          dispatched_at: string | null
          id: string
          notes: string | null
          order_id: string
          organization_id: string
          status: string
          total_amount: number
          updated_at: string
          vehicle_id: string | null
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          customer_id: string
          delivery_date?: string
          delivery_number: string
          dispatch_note?: string | null
          dispatch_status?: string
          dispatched_at?: string | null
          id?: string
          notes?: string | null
          order_id: string
          organization_id: string
          status?: string
          total_amount?: number
          updated_at?: string
          vehicle_id?: string | null
        }
        Update: {
          created_at?: string
          created_by?: string | null
          customer_id?: string
          delivery_date?: string
          delivery_number?: string
          dispatch_note?: string | null
          dispatch_status?: string
          dispatched_at?: string | null
          id?: string
          notes?: string | null
          order_id?: string
          organization_id?: string
          status?: string
          total_amount?: number
          updated_at?: string
          vehicle_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "delivery_notes_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "app_users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "delivery_notes_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "delivery_notes_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "delivery_notes_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "delivery_notes_vehicle_id_fkey"
            columns: ["vehicle_id"]
            isOneToOne: false
            referencedRelation: "vehicles"
            referencedColumns: ["id"]
          },
        ]
      }
      inventory_movements: {
        Row: {
          created_at: string
          created_by: string | null
          id: string
          metadata: Json
          movement_type: string
          notes: string | null
          organization_id: string
          product_id: string
          quantity_delta: number
          receipt_id: string | null
          receipt_item_id: string | null
          reference_number: string | null
          stock_after: number
          stock_before: number
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          id?: string
          metadata?: Json
          movement_type: string
          notes?: string | null
          organization_id: string
          product_id: string
          quantity_delta: number
          receipt_id?: string | null
          receipt_item_id?: string | null
          reference_number?: string | null
          stock_after: number
          stock_before: number
        }
        Update: {
          created_at?: string
          created_by?: string | null
          id?: string
          metadata?: Json
          movement_type?: string
          notes?: string | null
          organization_id?: string
          product_id?: string
          quantity_delta?: number
          receipt_id?: string | null
          receipt_item_id?: string | null
          reference_number?: string | null
          stock_after?: number
          stock_before?: number
        }
        Relationships: [
          {
            foreignKeyName: "inventory_movements_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "app_users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inventory_movements_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inventory_movements_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inventory_movements_receipt_id_fkey"
            columns: ["receipt_id"]
            isOneToOne: false
            referencedRelation: "inventory_receipts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inventory_movements_receipt_item_id_fkey"
            columns: ["receipt_item_id"]
            isOneToOne: false
            referencedRelation: "inventory_receipt_items"
            referencedColumns: ["id"]
          },
        ]
      }
      inventory_receipt_items: {
        Row: {
          created_at: string
          id: string
          organization_id: string
          product_id: string
          quantity_received: number
          receipt_id: string
          stock_after: number
          stock_before: number
          unit: string
          unit_cost: number
        }
        Insert: {
          created_at?: string
          id?: string
          organization_id: string
          product_id: string
          quantity_received: number
          receipt_id: string
          stock_after: number
          stock_before: number
          unit: string
          unit_cost: number
        }
        Update: {
          created_at?: string
          id?: string
          organization_id?: string
          product_id?: string
          quantity_received?: number
          receipt_id?: string
          stock_after?: number
          stock_before?: number
          unit?: string
          unit_cost?: number
        }
        Relationships: [
          {
            foreignKeyName: "inventory_receipt_items_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inventory_receipt_items_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inventory_receipt_items_receipt_id_fkey"
            columns: ["receipt_id"]
            isOneToOne: false
            referencedRelation: "inventory_receipts"
            referencedColumns: ["id"]
          },
        ]
      }
      inventory_receipts: {
        Row: {
          created_at: string
          created_by: string | null
          id: string
          notes: string | null
          organization_id: string
          receipt_number: string
          received_at: string
          supplier_name: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          id?: string
          notes?: string | null
          organization_id: string
          receipt_number: string
          received_at?: string
          supplier_name?: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          id?: string
          notes?: string | null
          organization_id?: string
          receipt_number?: string
          received_at?: string
          supplier_name?: string
        }
        Relationships: [
          {
            foreignKeyName: "inventory_receipts_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "app_users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inventory_receipts_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      order_items: {
        Row: {
          cost_price: number
          created_at: string
          id: string
          line_total: number
          notes: string | null
          order_id: string
          organization_id: string
          product_id: string
          product_sale_unit_id: string | null
          quantity: number
          quantity_in_base_unit: number
          sale_unit_label: string
          sale_unit_ratio: number
          unit_price: number
          updated_at: string
        }
        Insert: {
          cost_price?: number
          created_at?: string
          id?: string
          line_total: number
          notes?: string | null
          order_id: string
          organization_id: string
          product_id: string
          product_sale_unit_id?: string | null
          quantity: number
          quantity_in_base_unit?: number
          sale_unit_label: string
          sale_unit_ratio?: number
          unit_price: number
          updated_at?: string
        }
        Update: {
          cost_price?: number
          created_at?: string
          id?: string
          line_total?: number
          notes?: string | null
          order_id?: string
          organization_id?: string
          product_id?: string
          product_sale_unit_id?: string | null
          quantity?: number
          quantity_in_base_unit?: number
          sale_unit_label?: string
          sale_unit_ratio?: number
          unit_price?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "order_items_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_items_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_items_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_items_product_sale_unit_id_fkey"
            columns: ["product_sale_unit_id"]
            isOneToOne: false
            referencedRelation: "product_sale_units"
            referencedColumns: ["id"]
          },
        ]
      }
      order_number_counters: {
        Row: {
          last_number: number
          organization_id: string
        }
        Insert: {
          last_number?: number
          organization_id: string
        }
        Update: {
          last_number?: number
          organization_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "order_number_counters_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: true
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      orders: {
        Row: {
          created_at: string
          customer_id: string
          fulfillment_status: string
          id: string
          metadata: Json
          notes: string | null
          order_date: string
          order_number: string
          organization_id: string
          placed_by_user_id: string | null
          requested_delivery_date: string | null
          status: Database["public"]["Enums"]["order_status"]
          subtotal_amount: number
          total_amount: number
          updated_at: string
          verified_by_user_id: string | null
        }
        Insert: {
          created_at?: string
          customer_id: string
          fulfillment_status?: string
          id?: string
          metadata?: Json
          notes?: string | null
          order_date?: string
          order_number: string
          organization_id: string
          placed_by_user_id?: string | null
          requested_delivery_date?: string | null
          status?: Database["public"]["Enums"]["order_status"]
          subtotal_amount?: number
          total_amount?: number
          updated_at?: string
          verified_by_user_id?: string | null
        }
        Update: {
          created_at?: string
          customer_id?: string
          fulfillment_status?: string
          id?: string
          metadata?: Json
          notes?: string | null
          order_date?: string
          order_number?: string
          organization_id?: string
          placed_by_user_id?: string | null
          requested_delivery_date?: string | null
          status?: Database["public"]["Enums"]["order_status"]
          subtotal_amount?: number
          total_amount?: number
          updated_at?: string
          verified_by_user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "orders_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_placed_by_user_id_fkey"
            columns: ["placed_by_user_id"]
            isOneToOne: false
            referencedRelation: "app_users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_verified_by_user_id_fkey"
            columns: ["verified_by_user_id"]
            isOneToOne: false
            referencedRelation: "app_users"
            referencedColumns: ["id"]
          },
        ]
      }
      organizations: {
        Row: {
          created_at: string
          id: string
          is_active: boolean
          metadata: Json
          name: string
          slug: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          is_active?: boolean
          metadata?: Json
          name: string
          slug: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          is_active?: boolean
          metadata?: Json
          name?: string
          slug?: string
          updated_at?: string
        }
        Relationships: []
      }
      product_categories: {
        Row: {
          created_at: string
          id: string
          is_active: boolean
          name: string
          organization_id: string
          sort_order: number
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          is_active?: boolean
          name: string
          organization_id: string
          sort_order?: number
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          is_active?: boolean
          name?: string
          organization_id?: string
          sort_order?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "product_categories_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      product_category_items: {
        Row: {
          created_at: string
          id: string
          organization_id: string
          product_category_id: string
          product_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          organization_id: string
          product_category_id: string
          product_id: string
        }
        Update: {
          created_at?: string
          id?: string
          organization_id?: string
          product_category_id?: string
          product_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "product_category_items_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_category_items_product_category_id_fkey"
            columns: ["product_category_id"]
            isOneToOne: false
            referencedRelation: "product_categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_category_items_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      product_images: {
        Row: {
          created_at: string
          id: string
          organization_id: string
          product_id: string
          public_url: string
          sort_order: number
          storage_path: string
        }
        Insert: {
          created_at?: string
          id?: string
          organization_id: string
          product_id: string
          public_url: string
          sort_order?: number
          storage_path: string
        }
        Update: {
          created_at?: string
          id?: string
          organization_id?: string
          product_id?: string
          public_url?: string
          sort_order?: number
          storage_path?: string
        }
        Relationships: [
          {
            foreignKeyName: "product_images_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_images_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      product_sale_units: {
        Row: {
          base_unit_quantity: number
          cost_mode: string
          created_at: string
          fixed_cost_price: number | null
          id: string
          is_active: boolean
          is_default: boolean
          min_order_qty: number
          organization_id: string
          product_id: string
          sort_order: number
          step_order_qty: number | null
          unit_label: string
          updated_at: string
        }
        Insert: {
          base_unit_quantity?: number
          cost_mode?: string
          created_at?: string
          fixed_cost_price?: number | null
          id?: string
          is_active?: boolean
          is_default?: boolean
          min_order_qty?: number
          organization_id: string
          product_id: string
          sort_order?: number
          step_order_qty?: number | null
          unit_label: string
          updated_at?: string
        }
        Update: {
          base_unit_quantity?: number
          cost_mode?: string
          created_at?: string
          fixed_cost_price?: number | null
          id?: string
          is_active?: boolean
          is_default?: boolean
          min_order_qty?: number
          organization_id?: string
          product_id?: string
          sort_order?: number
          step_order_qty?: number | null
          unit_label?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "product_sale_units_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_sale_units_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      products: {
        Row: {
          cost_price: number
          created_at: string
          id: string
          is_active: boolean
          metadata: Json
          name: string
          organization_id: string
          reserved_quantity: number
          sku: string
          stock_quantity: number
          unit: string
          updated_at: string
        }
        Insert: {
          cost_price?: number
          created_at?: string
          id?: string
          is_active?: boolean
          metadata?: Json
          name: string
          organization_id: string
          reserved_quantity?: number
          sku: string
          stock_quantity?: number
          unit?: string
          updated_at?: string
        }
        Update: {
          cost_price?: number
          created_at?: string
          id?: string
          is_active?: boolean
          metadata?: Json
          name?: string
          organization_id?: string
          reserved_quantity?: number
          sku?: string
          stock_quantity?: number
          unit?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "products_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      vehicles: {
        Row: {
          created_at: string
          created_by: string | null
          driver_name: string | null
          id: string
          is_active: boolean
          license_plate: string | null
          name: string
          organization_id: string
          sort_order: number
          updated_at: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          driver_name?: string | null
          id?: string
          is_active?: boolean
          license_plate?: string | null
          name: string
          organization_id: string
          sort_order?: number
          updated_at?: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          driver_name?: string | null
          id?: string
          is_active?: boolean
          license_plate?: string | null
          name?: string
          organization_id?: string
          sort_order?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "vehicles_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "app_users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "vehicles_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      adjust_delivery_note_item: {
        Args: {
          p_adjusted_by: string
          p_delivery_note_item_id: string
          p_new_quantity_delivered: number
          p_organization_id: string
        }
        Returns: undefined
      }
      allocate_requisition_document_numbers: {
        Args: { requested_at?: string; requested_count?: number }
        Returns: {
          document_no: string
          sequence_key: string
          sequence_value: number
        }[]
      }
      create_app_session: {
        Args: { p_ip_hash?: string; p_user_agent?: string; p_user_id: string }
        Returns: {
          display_name: string
          expires_at: string
          organization_id: string
          role: Database["public"]["Enums"]["app_role"]
          session_id: string
        }[]
      }
      create_delivery_note: {
        Args: {
          p_created_by: string
          p_customer_id: string
          p_delivery_date: string
          p_items: Json
          p_notes: string
          p_order_id: string
          p_organization_id: string
          p_vehicle_id: string
        }
        Returns: string
      }
      create_inventory_receipt: {
        Args: {
          p_created_by: string
          p_items: Json
          p_notes: string
          p_organization_id: string
          p_receipt_number: string
          p_received_at: string
          p_supplier_name: string
        }
        Returns: string
      }
      create_store_delivery_note: {
        Args: {
          p_created_by: string
          p_customer_id: string
          p_delivery_date: string
          p_items: Json
          p_notes: string
          p_order_ids: string[]
          p_organization_id: string
          p_vehicle_id: string
        }
        Returns: string
      }
      get_order_daily_store_items: {
        Args: {
          p_customer_id: string
          p_order_date: string
          p_organization_id: string
        }
        Returns: {
          current_stock_quantity: number
          deliverable_quantity: number
          image_url: string
          line_total: number
          order_rounds: number
          ordered_quantity: number
          product_id: string
          product_name: string
          product_sku: string
          product_unit: string
          short_quantity: number
          unit_price: number
        }[]
      }
      get_order_daily_store_summaries: {
        Args: {
          p_limit?: number
          p_offset?: number
          p_order_date: string
          p_organization_id: string
          p_search?: string
        }
        Returns: {
          customer_code: string
          customer_id: string
          customer_name: string
          latest_order_at: string
          order_rounds: number
          product_count: number
          shortage_product_count: number
          total_amount: number
          total_quantity: number
        }[]
      }
      next_billing_number: {
        Args: { p_billing_date: string; p_organization_id: string }
        Returns: string
      }
      next_customer_code: {
        Args: { p_organization_id: string }
        Returns: string
      }
      next_delivery_note_number: {
        Args: { p_delivery_date: string; p_organization_id: string }
        Returns: string
      }
      next_order_number: {
        Args: { p_order_date: string; p_organization_id: string }
        Returns: string
      }
      record_pin_auth_result: {
        Args: {
          p_attempted_lookup: string
          p_ip_hash?: string
          p_success: boolean
          p_user_agent?: string
          p_user_id: string
        }
        Returns: {
          failed_pin_attempts: number
          locked_until: string
        }[]
      }
      revoke_app_session: { Args: { p_session_id: string }; Returns: undefined }
    }
    Enums: {
      app_role: "admin" | "member" | "warehouse"
      order_status: "draft" | "submitted" | "confirmed" | "cancelled"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      app_role: ["admin", "member", "warehouse"],
      order_status: ["draft", "submitted", "confirmed", "cancelled"],
    },
  },
} as const
